.github/PULL_REQUEST_TEMPLATE.md
.gitignore
README.md
package-lock.json
package.json
package.sh
serverless.yml
spec/helpers/reporter.ts
spec/support/jasmine.json
src/common/application/api/HttpStatus.ts
src/common/application/api/Response.ts
src/common/application/utils/__tests__/createResponse.spec.ts
src/common/application/utils/createResponse.ts
src/common/application/utils/logger.ts
src/functions/postResult/framework/__tests__/handler.spec.ts
src/functions/postResult/framework/handler.ts
tsconfig.json
tslint.json
webpack-sls-offline.config.js
webpack.config.js

* Create simple POST endpoint `/test-result` which responds HTTP 201.

MES-2137: Initial bootstrap from microservice template

---

package-lock.json
package.json
src/common/application/utils/__tests__/createResponse.spec.ts
src/functions/postResult/application/decompression-service.ts
src/functions/postResult/application/save-result-service.ts
src/functions/postResult/domain/errors/test-result-decompression-error.ts
src/functions/postResult/framework/__tests__/handler.spec.ts
src/functions/postResult/framework/handler.ts

* Partial PR for this story to unblock MES-2340/MES-2341
* Call a currently unimplemented service to decompress the test result body
* Pass the decompressed result to a facade that will eventually save to Aurora - currently does nothing

MES-2295: Implement basics of handler for postResult

---

package-lock.json
package.json
src/common/framework/config/config-helpers.ts
src/common/framework/config/config.ts
src/common/framework/mysql/database.ts
src/functions/postResult/application/__tests__/data/decompression-service.spec.data.ts
src/functions/postResult/application/__tests__/decompression-service.spec.ts
src/functions/postResult/application/decompression-service.ts
src/functions/postResult/application/save-result-service.ts
src/functions/postResult/domain/processing-status.ts
src/functions/postResult/domain/result-integration.ts
src/functions/postResult/domain/result-status.ts
src/functions/postResult/framework/__tests__/handler.spec.ts
src/functions/postResult/framework/config/config.ts
src/functions/postResult/framework/database/query-builder.ts
src/functions/postResult/framework/handler.ts
tsconfig.json
webpack.config.js

* Get IAM credentials so we can access RDS (code from the pollers)
* Build the insert queries for `TEST_RESULT` and `UPLOAD_QUEUE` tables
* Populate parameters for the inserts from the test result model
* Save the 4 records in a transaction with rollbacks on errors
* Still needs some tests for the more integration heavy parts, could well be in a subsequent PR

MES-2295: Get RDS IAM config + save result to Aurora

---

package-lock.json
package.json
src/functions/postResult/application/save-result-service.ts
src/functions/postResult/domain/__tests__/mes-joi-schema-service.spec.ts
src/functions/postResult/domain/mes-joi-schema-service.ts
src/functions/postResult/framework/__tests__/handler.spec.ts
src/functions/postResult/framework/database/query-builder.ts
src/functions/postResult/framework/handler.ts
tsconfig.json

- Uses Enjoi to convert MES schema to Joi.
- Validate data against Joi schema
- Return Http 500 if `ValidationResult` contains errors
- If errors are contained in `ValidationResult` set `ResultStatus` to `error`

Feature mes 2341 validate json object

---

package-lock.json
package.json
src/common/application/api/HttpStatus.ts
src/functions/postResult/framework/__tests__/handler.spec.ts
src/functions/postResult/framework/handler.ts

Compare the employeeId from JWT with the staffId from the test before pushing the test.

Feature mes 2340 check examiner jwt

---

serverless.yml
src/functions/getNextUpdateBatch/application/next-update-batch-service.ts
src/functions/getNextUpdateBatch/domain/interface-types.ts
src/functions/getNextUpdateBatch/framework/database/query-builder.ts
src/functions/getNextUpdateBatch/framework/handler.ts
src/functions/getNextUpdateBatch/framework/repositories/batch-repository.ts
src/functions/getNextUpdateBatch/framework/repositories/tars-batch-repository.ts
src/functions/postResult/domain/mes-joi-schema-service.ts
src/functions/postResult/framework/handler.ts

- Template code for `getNextUpdateBatch` lambda

MES-2324: Lambda template

---

serverless.yml
src/functions/updateUploadStatus/framework/handler.ts

Created the template lambda function to unblock Ops/Infra work.

Mes 2325 update upload status

---

serverless.yml
src/functions/getNextUpdateBatch/application/next-update-batch-service.ts
src/functions/getNextUpdateBatch/domain/interface-types.ts
src/functions/getNextUpdateBatch/framework/database/query-builder.ts
src/functions/getNextUpdateBatch/framework/handler.ts
src/functions/getNextUpdateBatch/framework/repositories/batch-repository.ts
src/functions/getNextUpdateBatch/framework/repositories/tars-batch-repository.ts
src/functions/getNextUploadBatch/application/next-update-batch-service.ts
src/functions/getNextUploadBatch/domain/batch-request-param-errors.ts
src/functions/getNextUploadBatch/domain/interface-types.ts
src/functions/getNextUploadBatch/domain/test-results.ts
src/functions/getNextUploadBatch/framework/__tests__/handler.spec.ts
src/functions/getNextUploadBatch/framework/database/__tests__/query-builder.spec.ts
src/functions/getNextUploadBatch/framework/database/query-builder.ts
src/functions/getNextUploadBatch/framework/handler.ts
src/functions/getNextUploadBatch/framework/repositories/batch-repository-interface.ts
src/functions/getNextUploadBatch/framework/repositories/batch-repository.ts

- Create a query to return test result json
- Added repositories to handle each interface type (only tars implemented)
- Compress data

Feature mes 2324 next batch implementation

---

src/functions/getNextUploadBatch/application/next-update-batch-service.ts
src/functions/getNextUploadBatch/domain/batch-request-param-errors.ts
src/functions/getNextUploadBatch/framework/__tests__/handler.spec.ts
src/functions/getNextUploadBatch/framework/handler.ts

- Created a simple Joi schema to validate interfaceType and batchSize

DES-2324: Handle validation using a simple Joi schema

---

src/functions/postResult/application/__tests__/hasCandidateCommunicationPermission.spec.ts
src/functions/postResult/application/__tests__/isCompletedTest.spec.ts
src/functions/postResult/application/hasCandidateCommunicationPermission.ts
src/functions/postResult/application/isCompletedTest.ts
src/functions/postResult/application/save-result-service.ts

adds conditions for adding to notify upload queue

---

src/functions/postResult/framework/database/query-builder.ts
src/functions/postResult/framework/handler.ts
src/functions/updateUploadStatus/application/update-upload-service.ts
src/functions/updateUploadStatus/framework/__tests__/handler.spec.ts
src/functions/updateUploadStatus/framework/database/__tests__/query-builder.spec.ts
src/functions/updateUploadStatus/framework/database/query-builder.ts
src/functions/updateUploadStatus/framework/handler.ts

Creating the Update Upload Status Lambda. The TARS UPLOAD lambda will call this to update each individual UPLOAD_QUEUE table record after processing to record the new state.
https://jira.i-env.net/browse/MES-2325
Outlined here: https://wiki.i-env.net/display/MES/Low+Level+Design+-+Test+Results+Microservice

MES-2325 - Update Upload Status

---

src/functions/getNextUploadBatch/domain/test-results.ts
src/functions/getNextUploadBatch/framework/database/query-builder.ts
src/functions/getNextUploadBatch/framework/handler.ts
src/functions/getNextUploadBatch/framework/repositories/batch-repository.ts

- Adding call to bootstrap the configuration
- Updating query to remove interpolation and include an args array

DES-2324: Bootstrapping config

---

src/functions/updateUploadStatus/framework/__tests__/handler.spec.ts
src/functions/updateUploadStatus/framework/handler.ts

* Make path parameter match that configured for APIG

Ensure we use app-ref for application reference path param on updateUploadStatus, not id

---

serverless.yml
src/functions/postResult/application/__tests__/jwt-verification-service.spec.ts
src/functions/postResult/application/jwt-verification-service.ts
src/functions/postResult/framework/__tests__/handler.spec.data.ts
src/functions/postResult/framework/__tests__/handler.spec.ts
src/functions/postResult/framework/handler.ts

Extracted JWT Authentication to its own service and added tests. Fixed where staffId was being grabbed from path params instead of the test data.
Also fixed path parameter for UUS lambda from {id} to {app-ref}

MES-2340 - Fixed jwt auth function bug

---

src/functions/postResult/framework/database/query-builder.ts

Ensure that UPLOAD_QUEUE records start with PROCESSING status, not ACCEPTED

---

package-lock.json
package.json
src/functions/postResult/domain/__tests__/mes-joi-schema-service.spec.ts
src/functions/postResult/framework/__tests__/handler.spec.data.ts
src/functions/postResult/framework/database/__tests__/query-builder.spec.data.ts

Upgrade to test schema version not expecting test ID in payload

---

src/functions/postResult/application/save-result-service.ts

amends condition to apply to NOTIFY, not RSIS

---

src/functions/postResult/framework/database/query-builder.ts

MES-2756 - Adds test centre cost code when posting result

---

package-lock.json
package.json
src/functions/postResult/domain/__tests__/mes-joi-schema-service.spec.ts

Upgrade to @dvsa/mes-test-schema@1.0.21 to accept RSIS fields such as examiner individualId

---

package-lock.json
package.json
src/functions/searchResults/framework/handler.ts

Changed return structure and corrected the application reference

---

serverless.yml
src/functions/getResult/framework/database/query-builder.ts
src/functions/getResult/framework/handler.ts
src/functions/getResult/framework/respositories/get-result-repository.ts
src/functions/searchResults/framework/handler.ts

MES-2821 - Scaffolding for getResult lambda

---

src/functions/searchResults/framework/handler.ts

Mes 2553 fixed query parameter bugs

---

package-lock.json
package.json
src/functions/searchResults/framework/handler.ts

MES-2550 - Fixes candidateName in response

---

serverless.yml
src/functions/retryProcessing/framework/handler.ts

create dummy lambda for retry processing to allow devops to create pipeline.

add dummy handler to unblock devops to create pipeline

---

src/functions/getResult/framework/__tests__/handler.spec.ts
src/functions/getResult/framework/database/__tests__/query-builder.spec.data.ts
src/functions/getResult/framework/database/__tests__/query-builder.spec.ts
src/functions/getResult/framework/database/query-builder.ts
src/functions/getResult/framework/handler.ts
src/functions/getResult/framework/repositories/get-result-repository.ts

Staff number is now not included in the query, will be re added once we can find out if the user is LDTM or not.
JIRA: https://jira.i-env.net/browse/MES-2894

Mes 2894 ignore staff number for now

---

package-lock.json
package.json
src/functions/postResult/domain/__tests__/mes-joi-schema-service.spec.ts
src/functions/postResult/framework/__tests__/handler.spec.data.ts
src/functions/postResult/framework/database/__tests__/query-builder.spec.data.ts

* Adopt @dvsa/mes-test-schema@1.0.23 to accept tests with new RSIS fields

MES-2811: Update test schema to accept new RSIS fields

---

src/functions/getResult/framework/__tests__/handler.spec.ts
src/functions/getResult/framework/handler.ts

Get Test Result - Use GzipSync

---

src/common/domain/user-role.ts
src/functions/searchResults/framework/__tests__/handler.spec.ts
src/functions/searchResults/framework/handler.ts

Using role set from the custom authorizer.

MES-2856: Use user role from request context

---

src/functions/postResult/framework/__tests__/handler.spec.ts
src/functions/postResult/framework/handler.ts

- Adds a new env var which can be set to bypass the staff id verification for performance testing

MES-2967 - Adding Bypass Flag

---

package-lock.json
package.json
src/functions/getResult/framework/__tests__/handler.spec.data.ts
src/functions/getResult/framework/__tests__/handler.spec.ts
src/functions/getResult/framework/database/__tests__/query-builder.spec.data.ts
src/functions/getResult/framework/database/__tests__/query-builder.spec.ts
src/functions/getResult/framework/database/query-builder.ts
src/functions/getResult/framework/handler.ts
src/functions/getResult/framework/repositories/get-result-repository.ts
src/functions/postResult/framework/database/query-builder.ts
src/functions/searchResults/framework/__tests__/handler.spec.data.ts
src/functions/searchResults/framework/database/__tests__/query-builder.spec.ts
src/functions/searchResults/framework/database/query-builder.ts
src/functions/searchResults/framework/handler.ts

- Updated all occurrences of `applicationReference` to use number instead of string
- Using new `mes-search-schema`
- Using mes-microservices-common `formatApplicationReference()` function to correctly format the application references

Mes 2954 fix app ref padding

---

package-lock.json
package.json
src/functions/postResult/application/__tests__/data/decompression-service.spec.data.ts
src/functions/postResult/framework/database/__tests__/query-builder.spec.data.ts
src/functions/searchResults/framework/__tests__/handler.spec.data.ts

Simple schema update for new format of eyesight test data.

MES-2994: Update test schema for eyesight serious fault change

---

package-lock.json
package.json

- Using latest Schema
- Ran npm audit

MES-3038 - Updated schema

---

src/functions/getNextUploadBatch/framework/handler.ts

- Added logging for batch size to help ensure the `getNextUploadBatch` lambda is not returning the same records multiple times.

MES -2954 - Added custom logging for batch size
